# Generated by Django 3.2.7 on 2021-10-18 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211018_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_rating_information',
            name='book_url',
        ),
    ]
