# Generated by Django 3.2.7 on 2021-10-18 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20211018_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_rating_information',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User_to_User', to='dashboard.information_user_detail'),
        ),
    ]
