# Generated by Django 3.2.7 on 2021-10-18 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information_user_detail',
            options={'verbose_name': 'User Information', 'verbose_name_plural': 'User Information'},
        ),
        migrations.AlterModelOptions(
            name='user_rating_information',
            options={'verbose_name': 'User Rating', 'verbose_name_plural': 'User Ratings'},
        ),
        migrations.AlterModelTable(
            name='information_user_detail',
            table='User_Info',
        ),
    ]
